#database specific configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springmicrodb
    username: root	
    password: root

#jpa specific configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update			
 
message: Welcome to production
databaseName: Couchbase
        